### PR TITLE
Fixed wrong case in #include leading to compilation error with MinGW and Posix threads

### PR DESCRIPTION
**Pull request by kivadiu**

### CODE REVIEW

**Comment by olk** [comment]
could you re-apply your pull-request to branch develop, please?

**Comment by pgroke-dt** [comment]
Are you sure that the lower "w" is more common if SDKs for cross-compiling? Because most SDKs from MS use a capital "W" nowadays...

**Comment by kivadiu** [comment]
> Are you sure that the lower "w" is more common if SDKs for cross-compiling? Because most SDKs from MS use a capital "W" nowadays...

I use W64 5.0.2.
What else do you know I could compare with?
Would you therefore suggest to put it between #ifdef mingw-64 #endif?

Frédéric

**Comment by kivadiu** [comment]
> could you re-apply your pull-request to branch develop, please?

done: https://github.com/boostorg/fiber/pull/135

Frédéric

**Comment by kivadiu** [comment]
Apparently MinGW (not W64) has also windows.h lower case in version 5.0.

**Comment by olk** [comment]
I'd like to get the pull-request for fiber's branch develop - without other
commits (your pull-requests contains unrelated, previously comits).

2017-07-12 13:18 GMT+02:00 Frédéric Bron <notifications@github.com>:

**Comment by olk** [comment]
wrong target branch - please provide it for branch develop

**Comment by pgroke-dt** [comment]
Frédéric, I don't know. For builds on Windows machines it won't be a problem. For cross-compiling ... don't know what the "common" casing is.

**Comment by kivadiu** [comment]
> wrong target branch - please provide it for branch develop

New try: https://github.com/boostorg/fiber/pull/136

**Pull request closed without merging**
