### PR TITLE
futex: add support for OpenBSD

### PR DESCRIPTION
**Pull request by brad0**
Add futex(2) support for OpenBSD.

### CODE REVIEW

**Comment by brad0** [comment]
Ping.

**Comment by brad0** [comment]
Ping.

**Comment by brad0** [comment]
Ping.

**Comment by Ericson2314** [comment]
I also this need. Will patch in Nixpkgs in the meantime.

**Comment by brad0** [comment]
@olk Ping.

**Comment by olk** [comment]
ty

**Pull request merged**
